package cn.com.sina.alan.service.ea.dao;

import cn.com.sina.alan.common.model.DeveloperModel;
import org.springframework.stereotype.Repository;

@Repository
public interface DeveloperModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer developerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer
     *
     * @mbggenerated
     */
    int insert(DeveloperModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer
     *
     * @mbggenerated
     */
    int insertSelective(DeveloperModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer
     *
     * @mbggenerated
     */
    DeveloperModel selectByPrimaryKey(Integer developerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeveloperModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeveloperModel record);
}