package cn.com.sina.alan.common.dao;

import cn.com.sina.alan.common.model.AdvertGroupModel;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AdvertGroupModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert_group
     *
     * @mbggenerated
     */
    int insert(AdvertGroupModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert_group
     *
     * @mbggenerated
     */
    int insertSelective(AdvertGroupModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert_group
     *
     * @mbggenerated
     */
    AdvertGroupModel selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdvertGroupModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdvertGroupModel record);

    List<AdvertGroupModel> findBy(AdvertGroupModel example);
    long countFindBy(AdvertGroupModel example);
}