package cn.com.sina.alan.common.dao;

import cn.com.sina.alan.common.model.KeyModel;
import org.springframework.stereotype.Repository;

@Repository
public interface KeyModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer keyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbggenerated
     */
    int insert(KeyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbggenerated
     */
    int insertSelective(KeyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbggenerated
     */
    KeyModel selectByPrimaryKey(Integer keyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KeyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_key
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KeyModel record);

    KeyModel selectByPublicKey(String pubKey);
}