package cn.com.sina.alan.common.model;

import java.math.BigDecimal;
import java.util.Date;

public class AdvertGroupModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.group_id
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.customer_id
     *
     * @mbggenerated
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.day_budget
     *
     * @mbggenerated
     */
    private BigDecimal dayBudget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.delivery_date
     *
     * @mbggenerated
     */
    private String deliveryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.platform
     *
     * @mbggenerated
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.pause_time
     *
     * @mbggenerated
     */
    private Date pauseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.pause_num
     *
     * @mbggenerated
     */
    private Integer pauseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.send_status
     *
     * @mbggenerated
     */
    private Byte sendStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.service_line_code
     *
     * @mbggenerated
     */
    private String serviceLineCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.total_pv
     *
     * @mbggenerated
     */
    private Long totalPv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.total_click
     *
     * @mbggenerated
     */
    private Integer totalClick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.total_cost
     *
     * @mbggenerated
     */
    private BigDecimal totalCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.today_pv
     *
     * @mbggenerated
     */
    private Integer todayPv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.today_click
     *
     * @mbggenerated
     */
    private Integer todayClick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_group.today_cost
     *
     * @mbggenerated
     */
    private BigDecimal todayCost;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.group_id
     *
     * @return the value of advert_group.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.group_id
     *
     * @param groupId the value for advert_group.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.group_name
     *
     * @return the value of advert_group.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.group_name
     *
     * @param groupName the value for advert_group.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.customer_id
     *
     * @return the value of advert_group.customer_id
     *
     * @mbggenerated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.customer_id
     *
     * @param customerId the value for advert_group.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.day_budget
     *
     * @return the value of advert_group.day_budget
     *
     * @mbggenerated
     */
    public BigDecimal getDayBudget() {
        return dayBudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.day_budget
     *
     * @param dayBudget the value for advert_group.day_budget
     *
     * @mbggenerated
     */
    public void setDayBudget(BigDecimal dayBudget) {
        this.dayBudget = dayBudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.delivery_date
     *
     * @return the value of advert_group.delivery_date
     *
     * @mbggenerated
     */
    public String getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.delivery_date
     *
     * @param deliveryDate the value for advert_group.delivery_date
     *
     * @mbggenerated
     */
    public void setDeliveryDate(String deliveryDate) {
        this.deliveryDate = deliveryDate == null ? null : deliveryDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.status
     *
     * @return the value of advert_group.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.status
     *
     * @param status the value for advert_group.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.create_time
     *
     * @return the value of advert_group.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.create_time
     *
     * @param createTime the value for advert_group.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.update_time
     *
     * @return the value of advert_group.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.update_time
     *
     * @param updateTime the value for advert_group.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.platform
     *
     * @return the value of advert_group.platform
     *
     * @mbggenerated
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.platform
     *
     * @param platform the value for advert_group.platform
     *
     * @mbggenerated
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.pause_time
     *
     * @return the value of advert_group.pause_time
     *
     * @mbggenerated
     */
    public Date getPauseTime() {
        return pauseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.pause_time
     *
     * @param pauseTime the value for advert_group.pause_time
     *
     * @mbggenerated
     */
    public void setPauseTime(Date pauseTime) {
        this.pauseTime = pauseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.pause_num
     *
     * @return the value of advert_group.pause_num
     *
     * @mbggenerated
     */
    public Integer getPauseNum() {
        return pauseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.pause_num
     *
     * @param pauseNum the value for advert_group.pause_num
     *
     * @mbggenerated
     */
    public void setPauseNum(Integer pauseNum) {
        this.pauseNum = pauseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.send_status
     *
     * @return the value of advert_group.send_status
     *
     * @mbggenerated
     */
    public Byte getSendStatus() {
        return sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.send_status
     *
     * @param sendStatus the value for advert_group.send_status
     *
     * @mbggenerated
     */
    public void setSendStatus(Byte sendStatus) {
        this.sendStatus = sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.service_line_code
     *
     * @return the value of advert_group.service_line_code
     *
     * @mbggenerated
     */
    public String getServiceLineCode() {
        return serviceLineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.service_line_code
     *
     * @param serviceLineCode the value for advert_group.service_line_code
     *
     * @mbggenerated
     */
    public void setServiceLineCode(String serviceLineCode) {
        this.serviceLineCode = serviceLineCode == null ? null : serviceLineCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.total_pv
     *
     * @return the value of advert_group.total_pv
     *
     * @mbggenerated
     */
    public Long getTotalPv() {
        return totalPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.total_pv
     *
     * @param totalPv the value for advert_group.total_pv
     *
     * @mbggenerated
     */
    public void setTotalPv(Long totalPv) {
        this.totalPv = totalPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.total_click
     *
     * @return the value of advert_group.total_click
     *
     * @mbggenerated
     */
    public Integer getTotalClick() {
        return totalClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.total_click
     *
     * @param totalClick the value for advert_group.total_click
     *
     * @mbggenerated
     */
    public void setTotalClick(Integer totalClick) {
        this.totalClick = totalClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.total_cost
     *
     * @return the value of advert_group.total_cost
     *
     * @mbggenerated
     */
    public BigDecimal getTotalCost() {
        return totalCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.total_cost
     *
     * @param totalCost the value for advert_group.total_cost
     *
     * @mbggenerated
     */
    public void setTotalCost(BigDecimal totalCost) {
        this.totalCost = totalCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.today_pv
     *
     * @return the value of advert_group.today_pv
     *
     * @mbggenerated
     */
    public Integer getTodayPv() {
        return todayPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.today_pv
     *
     * @param todayPv the value for advert_group.today_pv
     *
     * @mbggenerated
     */
    public void setTodayPv(Integer todayPv) {
        this.todayPv = todayPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.today_click
     *
     * @return the value of advert_group.today_click
     *
     * @mbggenerated
     */
    public Integer getTodayClick() {
        return todayClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.today_click
     *
     * @param todayClick the value for advert_group.today_click
     *
     * @mbggenerated
     */
    public void setTodayClick(Integer todayClick) {
        this.todayClick = todayClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_group.today_cost
     *
     * @return the value of advert_group.today_cost
     *
     * @mbggenerated
     */
    public BigDecimal getTodayCost() {
        return todayCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_group.today_cost
     *
     * @param todayCost the value for advert_group.today_cost
     *
     * @mbggenerated
     */
    public void setTodayCost(BigDecimal todayCost) {
        this.todayCost = todayCost;
    }
}