package cn.com.sina.alan.common.model;

import java.util.Date;

public class DeveloperModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column developer.developer_id
     *
     * @mbggenerated
     */
    private Integer developerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column developer.sso_id
     *
     * @mbggenerated
     */
    private String ssoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column developer.sso_name
     *
     * @mbggenerated
     */
    private String ssoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column developer.developer_name
     *
     * @mbggenerated
     */
    private String developerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column developer.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column developer.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column developer.developer_id
     *
     * @return the value of developer.developer_id
     *
     * @mbggenerated
     */
    public Integer getDeveloperId() {
        return developerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column developer.developer_id
     *
     * @param developerId the value for developer.developer_id
     *
     * @mbggenerated
     */
    public void setDeveloperId(Integer developerId) {
        this.developerId = developerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column developer.sso_id
     *
     * @return the value of developer.sso_id
     *
     * @mbggenerated
     */
    public String getSsoId() {
        return ssoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column developer.sso_id
     *
     * @param ssoId the value for developer.sso_id
     *
     * @mbggenerated
     */
    public void setSsoId(String ssoId) {
        this.ssoId = ssoId == null ? null : ssoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column developer.sso_name
     *
     * @return the value of developer.sso_name
     *
     * @mbggenerated
     */
    public String getSsoName() {
        return ssoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column developer.sso_name
     *
     * @param ssoName the value for developer.sso_name
     *
     * @mbggenerated
     */
    public void setSsoName(String ssoName) {
        this.ssoName = ssoName == null ? null : ssoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column developer.developer_name
     *
     * @return the value of developer.developer_name
     *
     * @mbggenerated
     */
    public String getDeveloperName() {
        return developerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column developer.developer_name
     *
     * @param developerName the value for developer.developer_name
     *
     * @mbggenerated
     */
    public void setDeveloperName(String developerName) {
        this.developerName = developerName == null ? null : developerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column developer.create_time
     *
     * @return the value of developer.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column developer.create_time
     *
     * @param createTime the value for developer.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column developer.update_time
     *
     * @return the value of developer.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column developer.update_time
     *
     * @param updateTime the value for developer.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}