package cn.com.sina.alan.common.model;

import java.util.Date;

public class KeyModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_key.key_id
     *
     * @mbggenerated
     */
    private Integer keyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_key.developer_id
     *
     * @mbggenerated
     */
    private Integer developerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_key.pub_key
     *
     * @mbggenerated
     */
    private String pubKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_key.sec_key
     *
     * @mbggenerated
     */
    private String secKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_key.key_role
     *
     * @mbggenerated
     */
    private String keyRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_key.apply_time
     *
     * @mbggenerated
     */
    private Date applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_key.audit_time
     *
     * @mbggenerated
     */
    private Date auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_key.reason
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_key.frequency
     *
     * @mbggenerated
     */
    private Integer frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_key.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_key.key_id
     *
     * @return the value of api_key.key_id
     *
     * @mbggenerated
     */
    public Integer getKeyId() {
        return keyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_key.key_id
     *
     * @param keyId the value for api_key.key_id
     *
     * @mbggenerated
     */
    public void setKeyId(Integer keyId) {
        this.keyId = keyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_key.developer_id
     *
     * @return the value of api_key.developer_id
     *
     * @mbggenerated
     */
    public Integer getDeveloperId() {
        return developerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_key.developer_id
     *
     * @param developerId the value for api_key.developer_id
     *
     * @mbggenerated
     */
    public void setDeveloperId(Integer developerId) {
        this.developerId = developerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_key.pub_key
     *
     * @return the value of api_key.pub_key
     *
     * @mbggenerated
     */
    public String getPubKey() {
        return pubKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_key.pub_key
     *
     * @param pubKey the value for api_key.pub_key
     *
     * @mbggenerated
     */
    public void setPubKey(String pubKey) {
        this.pubKey = pubKey == null ? null : pubKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_key.sec_key
     *
     * @return the value of api_key.sec_key
     *
     * @mbggenerated
     */
    public String getSecKey() {
        return secKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_key.sec_key
     *
     * @param secKey the value for api_key.sec_key
     *
     * @mbggenerated
     */
    public void setSecKey(String secKey) {
        this.secKey = secKey == null ? null : secKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_key.key_role
     *
     * @return the value of api_key.key_role
     *
     * @mbggenerated
     */
    public String getKeyRole() {
        return keyRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_key.key_role
     *
     * @param keyRole the value for api_key.key_role
     *
     * @mbggenerated
     */
    public void setKeyRole(String keyRole) {
        this.keyRole = keyRole == null ? null : keyRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_key.apply_time
     *
     * @return the value of api_key.apply_time
     *
     * @mbggenerated
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_key.apply_time
     *
     * @param applyTime the value for api_key.apply_time
     *
     * @mbggenerated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_key.audit_time
     *
     * @return the value of api_key.audit_time
     *
     * @mbggenerated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_key.audit_time
     *
     * @param auditTime the value for api_key.audit_time
     *
     * @mbggenerated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_key.reason
     *
     * @return the value of api_key.reason
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_key.reason
     *
     * @param reason the value for api_key.reason
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_key.frequency
     *
     * @return the value of api_key.frequency
     *
     * @mbggenerated
     */
    public Integer getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_key.frequency
     *
     * @param frequency the value for api_key.frequency
     *
     * @mbggenerated
     */
    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_key.status
     *
     * @return the value of api_key.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_key.status
     *
     * @param status the value for api_key.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}